### ISSUE TITLE
Support for Stable Rust?

### ISSUE THREAD

**Issue by auronandace** [acheronfail/istat#17]
I noticed in `lib.rs` you use a feature: `#![feature(ip)]` which means you need to use a nightly toolchain to compile the project.

Is there a plan to allow to compile on stable please?

**Comment by acheronfail** [comment]
It was only for [a single method](https://doc.rust-lang.org/nightly/std/net/struct.Ipv6Addr.html#method.is_unicast_link_local) so [I've just hardcoded that](https://github.com/acheronfail/i3stat/commit/fae12e9) for now.

I'm probably going to rename this crate (see #14) so I'll release this change at the same time as the rename.
